### ISSUE TITLE
Is it OK to rely on the fact the io::Mock uses 8192 buffer?

### ISSUE THREAD

**Issue by vi** [stepfunc/tokio-mock-io#2]
The codec being tested sometimes returns chunks of data as soon as they arrive, without waiting for the maximum amount of data.

This makes it split big message into 8192-byte chunks when used with Mock.

Is it guranteed that future semver-compativle tokio-mock-io versions will use the same buffer size? Is there a io::Builder method to force buffer size to make sequence of reads from the mock object predictable?

**Comment by jadamcrain** [comment]
Hi @vi.  I'm not sure I understand the question. I **believe** that this crate makes reads completely predictable by enqueueing an exact amount via [Handle.read](https://docs.rs/sfio-tokio-mock-io/0.2.0/sfio_tokio_mock_io/struct.Handle.html#method.read). 

I created this crate to serve my needs to support testing of two other of my protocol crates. There were shortcomings IMO with the mocks in [tokio-test](https://crates.io/crates/tokio-test).

**Comment by vi** [comment]
Maybe those additional buffer boundaries appears in `FramedRead`, not in the mock itself.

**Comment by jadamcrain** [comment]
Yeah, no such splitting would occur with these mocks. They expect/replicate exactly what's described using the `Handle`.
